In [1]:
import numpy as np
import pandas as pd
import dask.dataframe as dd
from scipy import stats
from matplotlib.pyplot import figure
from sklearn.metrics.pairwise import cosine_similarity
from scipy.sparse import csr_matrix
import warnings

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction import text
from sklearn.metrics.pairwise import cosine_similarity


from sklearn.cluster import KMeans
import pandas as pd
from sklearn.preprocessing import MinMaxScaler


warnings.filterwarnings("ignore")
%matplotlib inline

## Customer Attribute Based Recommendation through clustering

We try to related articles based on their category, garment group and description and try to build a sparse matrix mapping out their similarities. This is a non personalized recommendation but understanding similar products (articles in this case) is necessary to build a model.

In [2]:
path = "../files/"

In [3]:
temp1_df = pd.read_csv(path+"article-content-similarity.csv")
temp2_df = pd.read_csv(path+"customers.csv")

In [4]:
customer_df = pd.read_csv(path+"customer_intelligence.csv")

In [5]:
feature_set = ['unique_items', 'unique_departments', 'preferred_sales_channel', 'preferred_week',
               'age', 'monetary_value']

In [6]:
km = KMeans(n_clusters=25)
y_predicted = km.fit_predict(customer_df[feature_set])
customer_df['cluster']=y_predicted
customer_df['cluster'].value_counts()

18    192169
8     144791
23    120947
1     111555
19    104686
13     92125
22     86794
4      71277
17     64447
9      63752
24     44878
14     42578
0      39663
7      35359
15     32760
3      29622
10     22565
11     18145
2      14802
21     12845
16      8935
5       4728
20      2099
6        656
12       103
Name: cluster, dtype: int64

In [7]:
customer_df.index=customer_df['customer_id']
customer_df

,customer_id,unique_items,unique_departments,preferred_sales_channel,preferred_week,age,monetary_value,cluster
customer_id,,,,,,,,
00000dbacae5abe5e23885899a1fa44253a17956c6d1c3d25f88aa139fdfc657,00000dbacae5abe5e23885899a1fa44253a17956c6d1c3...,19,15,2,5,49.0,0.648983,14
0000423b00ade91418cceaf3b26c6af3dd342b51fd051eec9c12fb36984420fa,0000423b00ade91418cceaf3b26c6af3dd342b51fd051e...,64,32,2,1,25.0,2.601932,3
000058a12d5b43e67d225668fa1f8d618c13dc232df0cad8ffe7ad4a1091e318,000058a12d5b43e67d225668fa1f8d618c13dc232df0ca...,14,11,2,5,24.0,0.704780,1
00005ca1c9ed5f5146b52ac8639a40ca9d57aeff4d1bd2c5feb1ca5dff07c43e,00005ca1c9ed5f5146b52ac8639a40ca9d57aeff4d1bd2...,2,1,2,6,54.0,0.060983,13
00006413d8573cd20ed7128e53b7b13819fe5cfc2d801fe7fc0f26dd8d65a85a,00006413d8573cd20ed7128e53b7b13819fe5cfc2d801f...,12,10,2,2,52.0,0.469695,4
...,...,...,...,...,...,...,...,...
ffffbbf78b6eaac697a8a5dfbfd2bfa8113ee5b403e4747568cac33e8c541831,ffffbbf78b6eaac697a8a5dfbfd2bfa8113ee5b403e474...,42,14,2,2,24.0,1.292356,9
ffffcd5046a6143d29a04fb8c424ce494a76e5cdf4fab53481233731b5c4f8b7,ffffcd5046a6143d29a04fb8c424ce494a76e5cdf4fab5...,79,32,2,0,21.0,1.807322,3
ffffcf35913a0bee60e8741cb2b4e78b8a98ee5ff2e6a1778d0116cffd259264,ffffcf35913a0bee60e8741cb2b4e78b8a98ee5ff2e6a1...,40,29,2,3,21.0,0.788932,9
ffffd7744cebcf3aca44ae7049d2a94b87074c3d4ffe38b2236865d949d4df6a,ffffd7744cebcf3aca44ae7049d2a94b87074c3d4ffe38...,6,5,2,6,18.0,0.209203,18
ffffd9ac14e89946416d80e791d064701994755c3ab686a1eaf3458c36f52241,ffffd9ac14e89946416d80e791d064701994755c3ab686...,1,1,2,2,65.0,0.084729,0

In [8]:
def split_dataframe(df, chunk_size = 10000): 
    chunks = list()
    num_chunks = len(df) // chunk_size + 1
    for i in range(num_chunks):
        chunks.append(df[i*chunk_size:(i+1)*chunk_size])
    return chunks

In [9]:
def similarity_checker(df):
    tbl = []
    chunks = split_dataframe(df, chunk_size=50000)
    for chunk in chunks:
        cosine_similarity_array = cosine_similarity(chunk)
        similarity_df = pd.DataFrame(data=cosine_similarity_array, 
                                 index=chunk.index,
                                 columns=chunk.index)
        for j, item in enumerate(similarity_df.index):
            top_10_matched_items = similarity_df[item].nlargest(n=10).index
            top10 = ",".join(str(v) for v in (list(top_10_matched_items[top_10_matched_items != item])))
            row = [item, top10]
            tbl.append(row)
    return tbl

In [10]:
s_df = pd.DataFrame(similarity_checker(customer_df[customer_df['cluster'] == 24][feature_set]))
print(s_df.shape)

for i in range(24):
    t_df2 = pd.DataFrame(similarity_checker(customer_df[customer_df['cluster'] == i][feature_set]))
    print(i)
    print(t_df2.shape)
    s_df = s_df.append(t_df2, ignore_index=True)
    print(s_df.shape)

(44878, 2)
0
(39663, 2)
(84541, 2)
1
(111555, 2)
(196096, 2)
2
(14802, 2)
(210898, 2)
3
(29622, 2)
(240520, 2)
4
(71277, 2)
(311797, 2)
5
(4728, 2)
(316525, 2)
6
(656, 2)
(317181, 2)
7
(35359, 2)
(352540, 2)
8
(144791, 2)
(497331, 2)
9
(63752, 2)
(561083, 2)
10
(22565, 2)
(583648, 2)
11
(18145, 2)
(601793, 2)
12
(103, 2)
(601896, 2)
13
(92125, 2)
(694021, 2)
14
(42578, 2)
(736599, 2)
15
(32760, 2)
(769359, 2)
16
(8935, 2)
(778294, 2)
17
(64447, 2)
(842741, 2)
18
(192169, 2)
(1034910, 2)
19
(104686, 2)
(1139596, 2)
20
(2099, 2)
(1141695, 2)
21
(12845, 2)
(1154540, 2)
22
(86794, 2)
(1241334, 2)
23
(120947, 2)
(1362281, 2)

In [11]:
s_df.to_csv(path + 'customer-similarity.csv')

In [12]:
s_df

,0,1
0,0006d1fc72f81261e70e74249ab2c348e21a093ba40f2a...,d523f088074aeb6acffbdbb4cd5d34c80c3f5bdf5c5acd...
1,0008d644deb96bdc0ca262f161cf6d5e9a4e619bb75faa...,cdf9e4c4ef02a13302df5bab58ecc0f9d0ccedb6f0e38d...
2,000989f72a2b8e5da2f4abafc86c2e213816fa2ff2a060...,fbfc09c1c26d474b461862d1f968f6571b41f61c5632a3...
3,000c324da8d94bd513ab0d80a235e47fa98d2cef98bd2f...,3ac7d3cc9a0ac907a2ad793b303167b867e16372021510...
4,000fa1b80857fa40bf25990bc1b1b65afc63923a8e4b57...,f6b82707bff81efe230c6e1aca8ad98ec5768dbcb91f14...
...,...,...
1362276,fffc8a9f1545e08fdf09f7dc3bd0736e1bdccceecca685...,df0213ca52528df87972a85e309fda527c0e7ff2b9f5c3...
1362277,fffd6ab5f39cf8c9802c50e1e48a857ecddd5122a11e97...,f982e23dda5ccf33cc6ad35ac33c3ab6ea92e993431192...
1362278,fffebb3ec427e5f7a4220d95878d42d4227cb3bc4cfa7e...,de488a60af1c8843070764645b48be0b590f3fa38205a9...
1362279,fffec7f7e9bc9270d49b39c870feba01d9367c53b31f54...,f61767cfbaaf183df62dd266324ebaebf536f55c03dc3f...
1362280,ffff1c80bd2dede87deda612527c3df06d2fb270b85602...,f1cf12aa7f66c1cede9bcb55642b5f176cf7a8cc5d9a74...